from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from .asset_builder import generate_assets
from .evidence_lock import lock_evidence
from .manuscript_builder import compile_manuscript
from .pack_builder import build_tr_e_upload_pack
from .qa import run_qa


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def _resolve_campaign_dir(evidence_root: Path, campaign_id: str) -> Path:
    if evidence_root.name == campaign_id and evidence_root.exists():
        return evidence_root
    return evidence_root / campaign_id


def _audit_recheck(*, audit_json: Path, out_path: Path) -> None:
    if not audit_json.exists():
        raise FileNotFoundError(audit_json)
    payload = json.loads(audit_json.read_text(encoding="utf-8"))
    summary = payload.get("summary", {})
    if not bool(summary.get("overall_pass", False)):
        raise RuntimeError(f"audit overall_pass is false: {audit_json}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _write_campaign_lock(*, campaign_id: str, campaign_dir: Path, out_path: Path) -> None:
    manifest_path = campaign_dir / "CAMPAIGN_MANIFEST.json"
    manifest = {}
    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception:
            manifest = {}

    git_sha = str(manifest.get("git_sha", ""))
    env_hash = str(manifest.get("env_hash", ""))

    tex = (
        "% Auto-generated by submit_v3. Do not edit by hand.\n"
        f"\\newcommand{{\\CampaignID}}{{{campaign_id.replace('_', '\\_')}}}\n"
        f"\\newcommand{{\\CampaignGitSHA}}{{{git_sha.replace('_', '\\_')}}}\n"
        f"\\newcommand{{\\CampaignEnvHash}}{{{env_hash.replace('_', '\\_')}}}\n"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(tex, encoding="utf-8")


def _ensure_metadata_template(out_submission_dir: Path) -> Path:
    tpl = out_submission_dir / "TR_E_METADATA_TEMPLATE.yaml"
    if tpl.exists():
        return tpl

    # Camera-ready defaults. No TODO_ placeholders: packing must be strict.
    tpl.parent.mkdir(parents=True, exist_ok=True)
    tpl.write_text(
        "title: Reliability-Aware Multi-UAV Routing under Communication Outage Risk and Soft Time Windows\n"
        "running_title: Reliability-Aware Multi-UAV Routing\n"
        "abstract: Urban UAV logistics must meet time-window service levels while maintaining reliable command-and-control connectivity. We study a reliability-aware multi-UAV routing problem in which arc-level communication outage risk, estimated from an air-to-ground channel model and base-station layouts, is integrated with an energy proxy and soft time windows via a calibrated objective. We evaluate a solver stack combining an OR-Tools heuristic for scalable planning, a HiGHS mixed-integer model for certificate-gated exact solutions and bounds, and a hard time-window baseline (PyVRP). All evidence is locked to an audited campaign with a conservative claim regime: exact with certificate for N<=10, bound-gap for N=20/40, and scalability-only reporting for N=80.\n"
        "keywords: UAV logistics; vehicle routing; soft time windows; communication outage risk; operational reliability; reproducible research\n"
        "authors: Alireza Abbaszadeh\n"
        "corresponding_author: Alireza Abbaszadeh (alireza.abbaszadeh8558@iau.ir)\n"
        "affiliations: Department of Computer Engineering, Islamic Azad University, Mashhad, Iran\n"
        "funding: No external funding.\n"
        "conflicts: The author declares no conflict of interest.\n"
        "data_code_availability: \"Locked evidence + manuscript build pipeline: https://github.com/alirezaabbaszadeh/uav-tr-e-submit-v3 (campaign journal_v3_full_20260219_000231). Computational repo: https://github.com/alirezaabbaszadeh/uav-tr-e-journal-repro.\"\n",
        encoding="utf-8",
    )
    return tpl


def _load_simple_yaml_kv(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        vv = v.strip()
        if (vv.startswith('"') and vv.endswith('"')) or (vv.startswith("'") and vv.endswith("'")):
            vv = vv[1:-1]
        out[k.strip()] = vv
    return out


def _write_submission_texts(*, campaign_id: str, out_submission_dir: Path) -> None:
    out_submission_dir.mkdir(parents=True, exist_ok=True)

    # Highlights (<=85 chars each).
    highlights = [
        "Communication-risk-aware multi-UAV routing with soft time windows.",
        "Positioning: fleet-level routing vs trajectory-level DRL micro-control.",
        "Campaign-locked evidence with audit gates and deterministic regeneration.",
        "Scalability-only reporting at N=80 with strict no-bound/no-gap policy.",
    ]
    (out_submission_dir / "proposal_highlights.txt").write_text("\n".join(highlights) + "\n", encoding="utf-8")

    # Table/Figure index.
    index = (
        f"# Table/Figure Index ({campaign_id})\n\n"
        "## Tables (generated)\n"
        "- `manuscript/tr_e/generated/tables/tab_positioning_micro_vs_macro.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_comm_params.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_tw_families.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_significance_summary.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_kpi_A.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_cost_A.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_kpi_B.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_cost_B.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_gap_A.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_gap_B.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_feas_A.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_feas_B.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_scalability_summary.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_managerial_support.tex`\n"
        "- `manuscript/tr_e/generated/tables/tab_risk_signal.tex`\n\n"
        "## Figures (generated)\n"
        "- `manuscript/tr_e/generated/figures/fig_scenario_overview.pdf`\n"
        "- `manuscript/tr_e/generated/figures/fig_bs_delta_effect.pdf`\n"
        "- `manuscript/tr_e/generated/figures/fig_tradeoff_lambda_tw.pdf`\n"
        "- `manuscript/tr_e/generated/figures/fig_scalability_summary.pdf`\n"
    )
    (out_submission_dir / f"TABLE_FIGURE_INDEX_{campaign_id}.md").write_text(index, encoding="utf-8")

    # Claim/evidence map (lightweight, manuscript-facing).
    claim_map = (
        f"# Claim-Evidence Map ({campaign_id})\n\n"
        "This package is evidence-locked; key claims are backed by the generated tables/figures:\n\n"
        "- C1 (Positioning): Table `tab_positioning_micro_vs_macro` + citations.\n"
        "- C2 (Core KPIs A/B): Tables `tab_kpi_A`, `tab_cost_A`, `tab_kpi_B`, `tab_cost_B`.\n"
        "- C3 (Bounds/gaps): Tables `tab_gap_A`, `tab_gap_B` (N in {20,40} only).\n"
        "- C4 (Feasibility): Tables `tab_feas_A`, `tab_feas_B`.\n"
        "- C5 (Robustness/managerial levers): Table `tab_managerial_support` + Figure `fig_bs_delta_effect`.\n"
        "- C6 (Statistics): Table `tab_significance_summary` (Holm-adjusted p-values + effect sizes).\n"
    )
    (out_submission_dir / f"CLAIM_EVIDENCE_MAP_{campaign_id}.md").write_text(claim_map, encoding="utf-8")

    # Checklist.
    checklist = (
        f"# TR-E Upload Checklist ({campaign_id})\n\n"
        "- [x] Evidence lock report generated (hashes recorded).\n"
        "- [x] Audit JSON indicates overall_pass=true.\n"
        "- [x] Tables/figures generated from locked artifacts only.\n"
        "- [x] Anonymous + camera-ready PDFs compiled.\n"
        "- [x] Upload pack ZIP built with SHA256SUMS.\n"
        "- [x] Huang et al. cited in positioning + related work (>=2 cites).\n"
    )
    (out_submission_dir / f"TR_E_UPLOAD_CHECKLIST_{campaign_id}.md").write_text(checklist, encoding="utf-8")

    # Cover letter.
    meta = _load_simple_yaml_kv(out_submission_dir / "TR_E_METADATA_TEMPLATE.yaml")
    title = meta.get("title", "Reliability-Aware Multi-UAV Routing")
    authors = meta.get("authors", "Corresponding Author")
    affiliation = meta.get("affiliations", "")
    corresponding = meta.get("corresponding_author", authors)

    email = ""
    if "(" in corresponding and ")" in corresponding:
        email = corresponding[corresponding.find("(") + 1 : corresponding.find(")")]
    elif "@" in corresponding:
        email = corresponding

    sig_lines = [authors]
    if affiliation:
        sig_lines.append(affiliation)
    if email:
        sig_lines.append(email)

    cover = (
        "Dear Editor,\n\n"
        f"Please consider my manuscript entitled \"{title}\" for publication in Transportation Research Part E. "
        "The paper addresses reliability-aware multi-UAV routing under arc-level communication outage risk and soft time windows, "
        "framing connectivity as an operational reliability attribute and providing managerial levers for SLA-oriented planning.\n\n"
        f"All reported results are locked to an audited campaign (ID: {campaign_id}); this submission pack includes the frozen "
        "artifacts and scripts to regenerate all tables and figures deterministically.\n\n"
        "Sincerely,\n"
        + "\n".join(sig_lines)
        + "\n"
    )
    (out_submission_dir / "cover_letter.txt").write_text(cover, encoding="utf-8")


def _write_exec_manifest(*, campaign_id: str, out_submission_dir: Path, out_manuscript_dir: Path) -> Path:
    manifest_path = out_submission_dir / f"MANUSCRIPT_EXEC_MANIFEST_{campaign_id}.json"

    artifacts: list[Path] = [
        out_manuscript_dir / "camera_ready" / "main.pdf",
        out_manuscript_dir / "anonymous" / "main.pdf",
        out_submission_dir / f"TR_E_UPLOAD_CHECKLIST_{campaign_id}.md",
        out_submission_dir / f"CLAIM_EVIDENCE_MAP_{campaign_id}.md",
        out_submission_dir / f"TABLE_FIGURE_INDEX_{campaign_id}.md",
        out_submission_dir / "proposal_highlights.txt",
        out_submission_dir / "cover_letter.txt",
        out_submission_dir / "TR_E_METADATA.yaml",
    ]

    items = []
    for p in artifacts:
        if not p.exists():
            continue
        items.append({"path": p.as_posix(), "bytes": p.stat().st_size, "sha256": _sha256(p)})

    payload = {
        "generated_at_utc": _utc_now(),
        "campaign_id": campaign_id,
        "artifacts": items,
    }
    manifest_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return manifest_path


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="submit_v3: evidence-locked TR-E manuscript pipeline (no rerun)")
    p.add_argument("--campaign-id", required=True)
    p.add_argument("--evidence-root", required=True, help="path to outputs/campaigns or the campaign dir")
    p.add_argument("--audit-json", required=True)
    p.add_argument("--mode", choices=["full"], default="full")
    p.add_argument("--pdf-variant", choices=["camera_ready", "anonymous"], default="camera_ready")
    p.add_argument("--resume", action="store_true")

    args = p.parse_args(argv)

    repo_root = Path(__file__).resolve().parents[2]
    evidence_root = Path(args.evidence_root).expanduser().resolve()
    audit_json = Path(args.audit_json).expanduser().resolve()

    campaign_dir = _resolve_campaign_dir(evidence_root, args.campaign_id)
    if not campaign_dir.exists():
        raise FileNotFoundError(campaign_dir)

    manuscript_root = repo_root / "manuscript" / "tr_e"
    out_submission_dir = repo_root / "out" / "submission"
    out_manuscript_dir = repo_root / "out" / "manuscript"

    out_submission_dir.mkdir(parents=True, exist_ok=True)
    (out_manuscript_dir / "camera_ready").mkdir(parents=True, exist_ok=True)
    (out_manuscript_dir / "anonymous").mkdir(parents=True, exist_ok=True)

    # S01: evidence lock.
    evidence_lock_json = out_submission_dir / f"EVIDENCE_LOCK_REPORT_{args.campaign_id}.json"
    lock_res = lock_evidence(campaign_dir=campaign_dir, out_json=evidence_lock_json)
    if not lock_res.passed:
        raise RuntimeError(f"evidence lock failed (missing: {lock_res.missing_files})")

    # S02: audit recheck.
    audit_recheck_json = out_submission_dir / f"AUDIT_RECHECK_{args.campaign_id}.json"
    _audit_recheck(audit_json=audit_json, out_path=audit_recheck_json)

    # S03: generate assets.
    base_cfg = repo_root / "configs" / "base.json"
    generate_assets(campaign_dir=campaign_dir, manuscript_root=manuscript_root, base_config_path=base_cfg)

    # S04: campaign lock snippet for manuscript.
    _write_campaign_lock(
        campaign_id=args.campaign_id,
        campaign_dir=campaign_dir,
        out_path=manuscript_root / "generated" / "campaign_lock.tex",
    )

    # S05: compile PDFs.
    compile_manuscript(
        repo_root=repo_root,
        manuscript_root=manuscript_root,
        outdir=out_manuscript_dir / "camera_ready",
        variant="camera_ready",
    )
    compile_manuscript(
        repo_root=repo_root,
        manuscript_root=manuscript_root,
        outdir=out_manuscript_dir / "anonymous",
        variant="anonymous",
    )

    # S06: submission artifacts.
    _ensure_metadata_template(out_submission_dir)
    _write_submission_texts(campaign_id=args.campaign_id, out_submission_dir=out_submission_dir)

    # Materialize metadata now (strict: no TODO_).
    # build_tr_e_upload_pack will also enforce this.
    from .pack_builder import materialize_metadata

    materialize_metadata(
        out_submission_dir / "TR_E_METADATA_TEMPLATE.yaml",
        out_submission_dir / "TR_E_METADATA.yaml",
    )

    # Exec manifest for pack.
    exec_manifest = _write_exec_manifest(
        campaign_id=args.campaign_id,
        out_submission_dir=out_submission_dir,
        out_manuscript_dir=out_manuscript_dir,
    )

    # S07: build upload pack.
    pack = build_tr_e_upload_pack(
        campaign_id=args.campaign_id,
        out_submission_dir=out_submission_dir,
        out_manuscript_dir=out_manuscript_dir,
        manuscript_root=manuscript_root,
        audit_recheck_json=audit_recheck_json,
        manifest_json=exec_manifest,
        pdf_variant=args.pdf_variant,
    )

    # S08: QA.
    _, qa_report = run_qa(
        campaign_id=args.campaign_id,
        out_submission_dir=out_submission_dir,
        out_manuscript_dir=out_manuscript_dir,
        manuscript_root=manuscript_root,
        audit_recheck_json=audit_recheck_json,
        evidence_lock_json=evidence_lock_json,
    )

    qa_path = out_submission_dir / f"FINAL_QA_REPORT_{args.campaign_id}.json"
    qa_path.write_text(json.dumps(qa_report, indent=2), encoding="utf-8")
    if not qa_report.get("passed", False):
        raise RuntimeError(f"final QA failed: {qa_report.get('checks')}")

    # Print a compact run summary for the CLI.
    summary = {
        "campaign_id": args.campaign_id,
        "campaign_dir": campaign_dir.as_posix(),
        "out_manuscript": out_manuscript_dir.as_posix(),
        "out_submission": out_submission_dir.as_posix(),
        "pack": pack.as_posix(),
        "qa": qa_path.as_posix(),
    }
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
